[package]
name = "noulith"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
num = "0.3.0"
num-iter = "0.1.43"
num-traits = "0.2.15"
rand = "0.8.5"
regex = "1"

[target.'cfg(target_arch="wasm32")'.dependencies]
wasm-bindgen = "0.2.74"
