[package]
name = "noulith"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
num = "0.4.0"
rand = "0.8.5"
regex = "1"
rustyline = { version = "10.0.0", optional = true }
rustyline-derive = { version = "0.7.0", optional = true }
chrono = "0.4"
reqwest = { version = "0.11", features = ["blocking"], optional = true }

[features]
cli = ["rustyline", "rustyline-derive"]
request = ["reqwest"]

[target.'cfg(target_arch="wasm32")'.dependencies]
wasm-bindgen = "0.2.74"
getrandom = { version = "0.2", features = ["js"] } # ???

[lib]
crate-type = ["cdylib", "rlib"]
